#server:
#  port: 19060

eureka:
  client:
    healthcheck:
      enabled: true

poc:
  datasource: 
         main: 
              jdbc-url: jdbc:mysql://rm-uf657pe908opn3261943-vpc-rw.mysql.rds.aliyuncs.com:3306/pocdb?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=round
              username: ENC(MFntvQKlgr+7tIenM2IUsTv6arZgndaN)
              password: ENC(atpVuco/88S2XuFJw/OBmJdRI1YKojTsf7LcNghOff8=)
              driver-class-name: com.mysql.jdbc.Driver
              type: com.zaxxer.hikari.HikariDataSource
              hikari:
                minimum-idle: 5
                maximum-pool-size: 15
                idle-timeout: 30000
                pool-name: poc-main
                max-lifetime: 1800000
                connection-timeout: 30000
                connection-test-query: SELECT 1
         slave: 
              jdbc-url: jdbc:mysql://rm-uf657pe908opn3261943-vpc-rw.mysql.rds.aliyuncs.com:3306/pocdb?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=round
              username: ENC(MFntvQKlgr+7tIenM2IUsTv6arZgndaN)
              password: ENC(atpVuco/88S2XuFJw/OBmJdRI1YKojTsf7LcNghOff8=)
              driver-class-name: com.mysql.jdbc.Driver
              type: com.zaxxer.hikari.HikariDataSource
              hikari:
                minimum-idle: 5
                maximum-pool-size: 15
                idle-timeout: 30000
                pool-name: poc-slave
                max-lifetime: 1800000
                connection-timeout: 30000
                connection-test-query: SELECT 1
feign:  
  hystrix:  
    enabled: true
  
logging:
  level:
    com.cups.poc: WARN
    jdbc.audit: ERROR
    jdbc.resultset: ERROR
    jdbc.sqlonly: ERROR

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

xxl:
 job:
   admin:
        addresses: http://job.poc.com:8080/xxl-job-admin
   executor:
        appname: xxl-job-executor-poc
        ip:
        port: 9062
        logpath: ./
        logretentiondays: -1
   accessToken:
