server:
  port: 8220
spring:
  application:
    name:  poc-monitor-service

eureka:
  instance:
    lease-expiration-duration-in-seconds: 30 
    lease-renewal-interval-in-seconds: 10
    preferIpAddress: true
    instance-id:  ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
        defaultZone:  http://dc1.poc.com:8205/eureka,http://dc2.poc.com:8206/eureka,http://dc3.poc.com:8207/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5

management:
  endpoints:
    web:
      exposure:
        include:  "*"
  endpoint:
    health:
      show-details: always

## Configuring info endpoint
info:
  app:
    name: ${spring.application.name}
    server-port: ${server.port}
    java-version: ${java.version}

